### ISSUE TITLE
AHAP: Unlocking the game on Steam failed.

### ISSUE THREAD

**Issue by MarkLindsay** [jasonrohrer/OneLife#1143]
The unlock fails and I can't log on to the AHAP servers. Could it be that my Steam email and OHOL email are not the same? Could it be that I'm on Ubuntu?

- I rode the rocket
- followed the link for "Your Another Planet off-Steam downloads"
- followed the login for Steam to unlock
- ended up with this fail message
    - ![image](https://github.com/user-attachments/assets/b47672cc-449b-4867-8578-429614a710d2)

Is it necessary to unlock it on Steam? Because before trying that I just put the AHAP key into my AHAP client and get "PLEASE DOWNLOAD THE LATEST VERSION" black screen. That lead me down tracing the version number settings.
- I built from source with [a modified script mentioned in this other issue](https://github.com/jasonrohrer/OneLife/issues/1142)
- manually changed serverCodeVersionNumber.txt to 42 (assumed per [here](http://onehouronelife.com/ahapVersion.txt))
- tried 41, and 43 because sometimes they are off by one, maybe?

**Comment by jasonrohrer** [comment]
Sorry about this!  Looking into it.

**Comment by jasonrohrer** [comment]
Actually, I don't think that "unlocking on steam" works for AHAP.  That works for OHOL, but the GrantPackage API has been phased out by Steam, I think, so that new games cannot use it.  I suppose it's a bug that the AHAP ticket server is even displaying that option, and I will fix that.

When you rode the rocket, you should have gotten a Steam Key.  I see it here for you.  I will email it to you.

Also, you shouldn't have to use Steam to play AHAP.

I'm sure there's some issue with the version number settings that you tweaked... I don't have time to help you with that, though.

But if you're really stuck, the Steam Key that I will send you is a good work-around.

**Comment by jasonrohrer** [comment]
Okay, I fixed the bug that was showing that "Unlock the game on Steam" thing on the TicketServer for AHPA.

**Comment by MarkLindsay** [comment]
Thanks for the help.

I still can't connect to the public servers.

1. I built with the [new script](https://github.com/jasonrohrer/OneLife/blob/4d1040d1f2dae7d642dde030f51664b095f6d5d5/scripts/pullAndBuildTestSystemAHAP.sh)
2. launched the vanilla client
3. put in my email and AHAP key
4. tried to connect to the public server
5. I get a screen that says "PLEASE DOWNLOAD THE LATEST VERSION".

That's all I've done.

**Comment by MarkLindsay** [comment]
Hold up. I've been putting the AHAP Steam key into the login fields in the AHAP client. That's not what you're supposed to do? It just looked like the OHOL key so I figured it's how you log in.

Now that I've put my OHOL key back, if I specify a public AHAP server, and use the vanilla client, I can connect.
