### ISSUE TITLE
Client displays other player's position incorrectly

### ISSUE THREAD

**Issue by kanikamu** [jasonrohrer/OneLife#123]
Here you can see someone abusing it: https://www.twitch.tv/videos/333312336?t=01h27m59s

Also people's heads seem to sometimes go behind objects that are behind them for some reason. Might have something to do with this.

**Comment by jasonrohrer** [comment]
You're talking about the knife fight there?

**Comment by laccy** [comment]
yeah i seen that too, he was moving a bit, than i lost the arrow, when he wasn't even moving, glitched himself out against bows

also happens to babies who run around and got to tell them to move cause they cannot be picked up
also happens when you build a wall on them, like smash adobe or put a bell base

**Comment by swallis21** [comment]
Can confirm this has happened to me a few times. Client displays them standing still, but uninteractable, just glitched in place while they're somewhere else. It only fixes itself when they do something in my view that requires them to be in a certain place.

**Comment by jasonrohrer** [comment]
The thing with their head being behind objects in the row behind them has been fixed.  There was a positional glitch client-side.

**Comment by JustinLove** [comment]
I'm still seeing some cases of this occur. Thus far, with some instrumentation, it seems fairly common, but only noticeable when there is an object to be out-of-order. I think I've got it down to the area around `Reached dest %f seconds early`, which sets currentPos and currentSpeed = 0, but not destination coordinates. Still have to figure out why endpos is not the destination coordinate.

I'm also beginning to suspect that this is the cause (or one of the causes) of not being able to pick up babies #128
