### ISSUE TITLE
Moonwalking

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#309]
Sometimes become stationary but legs continue to move. Can moonwalk, moonrun, and even moonhorseride.

Can happen pretty often.

**Comment by laccy** [comment]
it's when you stop moving before completed steps, in pvp at least it worked like that, when you step 2 in you are not in the tile yet but when you step one more you are in, the "griefer dance" which really should be called " the more experienced duelist dodge manuevers" xD
so if you cancel a move before 2 steps, you will still see animation

**Comment by jasonrohrer** [comment]
If someone can figure out how to reproduce this reliably, can you make a short recordedGame of yourself doing it (use a high-number server as Eve)?

**Comment by AlecYawata** [comment]
Reproduce is very easy.
I will post recordedGame.
And this is video what that happened.
https://www.twitch.tv/videos/439326927

**Comment by AlecYawata** [comment]
Trying eat food, has same problem as moonwalking.
Click twice youself with some food when you are full food value.

With eating berry.
[recordedGame000120.txt](https://github.com/jasonrohrer/OneLife/files/3292867/recordedGame000120.txt)

With horse-down card.
[recordedGame000122.txt](https://github.com/jasonrohrer/OneLife/files/3292874/recordedGame000122.txt)

**Comment by jasonrohrer** [comment]
Okay, finally made some progress on this.

The "moon eating" is fixed (where double-clicking to eat when full results in your stuck in the eating animation).

I think this is the same cause as moonwalking, but I haven't been able to confirm that.

When this week's update ships, please let me know if it's fixed.

ALSO:  do you know exact click steps to reproduce moonwalking?

**Comment by trevorhackman** [comment]
I finally saw this happen again while on a horse cart. Cases of it seem reduced but it's not fully fixed.

**Comment by trevorhackman** [comment]
I found a pretty consistent way to reproduce this. 

When standing at this location in the tutorial: https://puu.sh/ElSBw/594a6b1360.png

Clicking twice on one of the bottom right adobe walls can cause you to get visually stuck moonwalking between the tiles like this:  https://puu.sh/ElSBR/8e109ff725.png

There's some finesse to the timing of the clicks, doesn't always happen but I can get it to happen half the time. The first click hold down just briefly before an immediate second click.

**Comment by jasonrohrer** [comment]
YES!  This is what I was waiting for.

This method of reproducing the bug helped me track it down and fix it.
